// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package demo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Querier interface {
	// Finds knowledge chunks from mission reports that are semantically similar
	// to a given input embedding, ordered by similarity (vector cosine distance).
	FindSimilarMissionKnowledge(ctx context.Context, embedding pgvector.Vector) ([]FindSimilarMissionKnowledgeRow, error)
	// Fetches the structured facts for a single Apollo mission by its name.
	GetMissionFacts(ctx context.Context, missionName string) (VwApolloMissionFact, error)
	// Calculates the sum of all visitors for a single park across all recorded years.
	GetTotalVisitorsForPark(ctx context.Context, parkName string) (GetTotalVisitorsForParkRow, error)
	// Fetches all park visitation records, ordered by the highest visitor count first.
	ListParkVisitationRecords(ctx context.Context) ([]VwNpsVisitation, error)
	// Fetches all park visitation records for a specific state.
	ListParksByState(ctx context.Context, stateCode pgtype.Text) ([]VwNpsVisitation, error)
}

var _ Querier = (*Queries)(nil)
