# /backend/configs/ingestion/demo/apollo_mission_facts.yaml

# Unique identifier for this report type.
report_type: "APOLLO_MISSION_FACTS"

# The item_type for this data in the generic 'items' table.
item_type: "MISSION_FACTS"

# The business key is the unique Mission name.
business_key:
  - "Mission"

scope_field: "Program"

column_mappings:
  - csv_header: "Program"
    json_field: "Program"
    validation:
      required: true

  - csv_header: "Mission"
    json_field: "Mission"
    validation:
      required: true

  - csv_header: "Commander"
    json_field: "Commander"
    validation:
      required: false

  - csv_header: "LunarModulePilot"
    json_field: "LunarModulePilot"
    validation:
      required: false

  - csv_header: "LaunchDate"
    json_field: "LaunchDate"
    attempts:
      - transforms:
        - "to_date:2006-01-02"
    validation:
      required: true

  - csv_header: "LandingSite"
    json_field: "LandingSite"
    validation:
      required: false
